apiVersion: apps/v1
kind: Deployment
metadata:
 name: azure-sccproject2-springapp
spec:
 replicas: 1
 selector:
  matchLabels:
   app: azure-sccproject2-springapp
 template:
  metadata:
   labels:
    app: azure-sccproject2-springapp
  spec:
   nodeSelector:
    "beta.kubernetes.io/os": linux
   containers:
    - name: azure-sccproject2-springapp
      image: biagrilo98/sccproject2021
      ports:
       - containerPort: 8080
      env:
       - name: REDIS
         value: azure-redis-sccproject2
      volumeMounts:
       - mountPath: "/scc/data"
         name: volume
   volumes:
        - name: volume
          persistentVolumeClaim:
           claimName: azure-disk-volume
---
apiVersion: v1
kind: Service
metadata:
  name: azure-redis-sccproject2
spec:
  ports:
  - port: 6379
  selector:
    app: azure-redis-sccproject2
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: azure-redis-sccproject2
spec:
 replicas: 1
 selector:
  matchLabels:
   app: azure-redis-sccproject2
 template:
  metadata:
   labels:
    app: azure-redis-sccproject2
  spec:
   nodeSelector:
    "beta.kubernetes.io/os": linux
   containers:
    - name: azure-redis-sccproject2
      image: redis
      env:
       - name: ALLOW_EMPTY_PASSWORDS
         value: "yes"
      resources:
       requests:
        cpu: 100m
        memory: 128Mi
       limits:
        cpu: 250m
        memory: 256Mi
      ports:
       - containerPort: 6379
         name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: azure-sccproject2-springapp
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: azure-sccproject2-springapp
